apiVersion: v1
kind: ConfigMap
metadata:
  name: stremify-env
  namespace: stremify
data:
  scrape_built_in: "true"
  cache: "true"
  disable_same_ip_embeds: "true"
  foreign_provider_languages: "de,it,fr,es"
  name: "Stremify | ElfHosted"
  description: |
    <img src="https://elfhosted.com/images/logo.svg" height="72px" width="72px"/>

    <P>
      This is a free community instance, enjoy! â¤ï¸ </BR>(<I>reasonable <A HREF="https://github.com/elfhosted/infra/blob/main/traefik-middleware/middleware-rate-limit-public-stremio-addon.yaml">rate-limits</A> apply</I>)</BR>
    </BR><A HREF="https://elfhosted.com">ElfHosted</A> is an <A HREF="https://elfhosted.com/open/">open-source</A> PaaS built and run by a <A HREF="https://discord.elfhosted.com">friendly community of geeks</A>, which self-hosts <A HREF="https://elfhosted.com/guides/media/">your favorite streaming apps</A> for you, automatically and easily. 
    </P>
    <P>
      Individual, hosted premium <A HREF="https://store.elfhosted.com/product/stremify">Stremify</A> instances are available with higher rate-limits.
    </P>
    <h3>Why use <A HREF="https://elfhosted.com/stremio-addons/">ElfHosted Stremio addons</A>?</h3>
              <p style="text-align: justify;">
                    âœ… Highly-available, <A HREF="https://elfhosted.com/open/">open-source</A> infrastructure  / <A HREF="https://status.elfhosted.com/history/stremify-stremio-addon"><IMG SRC="https://img.shields.io/endpoint?url=https%3A%2F%2Fraw.githubusercontent.com%2Felfhosted%2Fstatus.elfhosted.com%2Fmaster%2Fapi%2Fstremify-stremio-addon%2Fuptime.json"></A><br/>
                    ğŸ“Š Geek out over <A HREF="https://fnky.nz/grafana-stremify">public performance metrics</A><br/>
              </p>		
