apiVersion: v1
kind: ConfigMap
metadata:
  name: deprecations-files
  namespace: deprecations
data:
  annatar-is-deprecated.json: |
    {
        "streams": [
            {
                "name": "[ğŸ˜¿] Annatar",
                "title": "Annatar is deprecated ",
                "torrentTitle": "Annatar is deprecated ğŸ˜¿\nğŸ¬ What now?"
                "url": "https://url-to-deprecated-md4"
            }
        ]
    }