apiVersion: v1
kind: ConfigMap
metadata:
  name: deprecations-files
  namespace: deprecations
data:
  annatar-is-deprecated.json: |
    {
        "streams": [
            {
                "name": "[ğŸ˜¿] Annatar",
                "title": "Annatar is deprecated ",
                "torrentTitle": "Annatar is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«",
                "url": "https://annatar-is-deprecated.elfhosted.com"
            }
        ]
    }
  stremio-jackett-is-deprecated.json: |
    {
        "streams": [
            {
                "name": "[ğŸ˜¿] Stremio-Jackett",
                "title": "Stremio-Jackett is deprecated ",
                "torrentTitle": "Stremio-Jackett is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«",
                "url": "https://stremio-jackett-is-deprecated.elfhosted.com"
            }
        ]
    }    
