apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-files
  namespace: demo-booklore
data:
  annatar-is-deprecated.json: |
    {
        "streams": [
            {
                "name": "[ğŸ˜¿] Annatar",
                "title": "Annatar is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nSee https://fnky.nz/sag",
                "torrentTitle": "Annatar is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nMore addons at https://fnky.nz/sag",
                "url": "https://elfhosted.com/assets/annatar-is-deprecated.mp4"
            }
        ]
    }
  shluflix-is-deprecated.json: |
    {
        "streams": [
            {
                "name": "[ğŸ˜¿] Shluflix",
                "title": "Shluflix is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nSee https://fnky.nz/sag",
                "torrentTitle": "Shuflix is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nMore addons at https://fnky.nz/sag",
                "url": "https://elfhosted.com/assets/shluflix-is-deprecated.mp4"
            }
        ]
    }
  stremio-jackett-is-deprecated.json: |
    {
        "streams": [
            {
                "name": "[ğŸ˜¿] Stremio-Jackett",
                "title": "Stremio-Jackett is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nSee https://fnky.nz/sag",
                "torrentTitle": "Stremio-Jackett is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nMore addons at https://fnky.nz/sag",
                "url": "https://elfhosted.com/assets/annatar-is-deprecated.mp4"
            }
        ]
    }   

  knightcrawler-is-deprecated.json: |
    {
        "streams": [
            {
                "name": "[ğŸ˜¿] KnightCrawler",
                "title": "KnightCrawler is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nSee https://fnky.nz/sag",
                "torrentTitle": "KnightCrawler is deprecated ğŸ˜¿\nUse MediaFusionğŸï¸ or CometğŸ’«\nMore addons at https://fnky.nz/sag",
                "url": "https://elfhosted.com/assets/knightcrawler-is-deprecated.mp4"
            }
        ]
    }   

  mediafusion-search-rate-limited.json: |
    {
        "streams": [
            {
                "name": "[ğŸ¢] MediaFusion",
                "title": "MediaFusion public rate-limit exceeded ğŸ¢",
                "torrentTitle": "Public rate-limit exceeded ğŸ¢\nSee https://fnky.nz/elf-stremio",
                "url": "https://elfhosted.com/assets/public-rate-limit-exceeded.mp4"
            }
        ]
    }  
  mediafusion-catalog-rate-limited.json: |
    {
    "metas": [
        {
        "id": "rate-limit-exceeded",
        "name": "MediaFusion public rate-limit exceeded ğŸ¢",
        "type": "movie",
        "poster": "https://docs.elfhosted.com/images/public-rate-limit-exceeded-movie-poster.png",
        "description": "Public rate-limit exceeded ğŸ¢\nSee https://fnky.nz/elf-stremio"
        }
     ]
    }  

  comet-search-rate-limited.json: |
    {
        "streams": [
            {
                "name": "[ğŸ¢] Comet",
                "title": "Comet public rate-limit exceeded ğŸ¢",
                "torrentTitle": "Public rate-limit exceeded ğŸ¢\nSee https://fnky.nz/elf-stremio",
                "url": "https://elfhosted.com/assets/public-rate-limit-exceeded.mp4"
            }
        ]
    } 
  aiostreams-search-rate-limited.json: |
    {
        "streams": [
            {
                "name": "[ğŸ¢] AIO",
                "title": "AIO Streams public rate-limit exceeded ğŸ¢",
                "torrentTitle": "Public rate-limit exceeded ğŸ¢\nSee https://fnky.nz/elf-stremio",
                "url": "https://elfhosted.com/assets/public-rate-limit-exceeded.mp4"
            }
        ]
    }    
  stremio-jackett-search-rate-limited.json: |
    {
        "streams": [
            {
                "name": "[ğŸ¢] Stremio-Jackett",
                "title": "Stremio-Jackett public rate-limit exceeded ğŸ¢",
                "torrentTitle": "Public rate-limit exceeded ğŸ¢\nSee https://fnky.nz/elf-stremio",
                "url": "https://elfhosted.com/assets/public-rate-limit-exceeded.mp4"
            }
        ]
    }  
  stremthru-search-rate-limited.json: |
    {
        "streams": [
            {
                "name": "[ğŸ¢] Stremthru",
                "title": "Stremthru public rate-limit exceeded ğŸ¢",
                "torrentTitle": "Public rate-limit exceeded ğŸ¢\nSee https://fnky.nz/elf-stremio",
                "url": "https://elfhosted.com/assets/public-rate-limit-exceeded.mp4"
            }
        ]
    }             
  jackettio-search-rate-limited.json: |
    {
        "streams": [
            {
                "name": "[ğŸ¢] Jackettio",
                "title": "Jackettio public rate-limit exceeded ğŸ¢",
                "torrentTitle": "Public rate-limit exceeded ğŸ¢\nSee https://fnky.nz/elf-stremio",
                "url": "https://elfhosted.com/assets/public-rate-limit-exceeded.mp4"
            }
        ]
    }                
