apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: comet-jackett.${dns_domain}
  namespace: comet
spec:
  routes:
    # "stream" endpoint is the one which invokes database access, and thus needs tighter rate-limiting
    - match: Host(`comet-jackett.${dns_domain}`)
      kind: Rule
      services:
        - name: jackett
          kind: Service
          port: 9117
      middlewares:  
        - name: bamb0uu-traefik-forward-auth
          namespace: aa-bamb0uu
          