apiVersion: v1
kind: Secret
metadata:
  name: comet-restic-config
  namespace: comet
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: s3:${volsync_restic_repository}/volsync/comet/comet
  # The repository encryption key
  RESTIC_PASSWORD: ${volsync_restic_password}
  # ENV vars specific to the chosen back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  AWS_ACCESS_KEY_ID: ${volsync_aws_access_key_id}
  AWS_SECRET_ACCESS_KEY: ${volsync_aws_secret_access_key}