apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seonaut
  namespace: flux-system
spec:
  interval: 15m
  path: seonaut
  prune: true # remove any elements later removed from the above path
  timeout: 10m # if not set, this defaults to interval duration, which is 1h
  sourceRef:
    kind: GitRepository
    name: infra
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: seonaut
      namespace: seonaut 
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
   