apiVersion: v1
kind: ConfigMap
metadata:
  name: servers-json
  namespace: librespeed
data:
  servers.json: |
    [
        {
            "name": "Falkenstein, Germany (elfhosted.com)",
            "server" :"//hobbit01-speed.elfhosted.com/",
            "dlURL" :"garbage.php",
            "ulURL" :"empty.php",
            "pingURL" :"empty.php",
            "getIpURL" :"getIP.php"
        },
        {
            "name": "Washington State, USA (elfhosted.us)",
            "server" :"//yankee01-speed.elfhosted.us/",
            "dlURL" :"garbage.php",
            "ulURL" :"empty.php",
            "pingURL" :"empty.php",
            "getIpURL" :"getIP.php"
        },
        {
            "name": "Auckland, New Zealand (elfhosted.tbc)",
            "server" :"//speedtest-auckland.elfhosted.com/",
            "dlURL" :"garbage.php",
            "ulURL" :"empty.php",
            "pingURL" :"empty.php",
            "getIpURL" :"getIP.php"
        },
        {
            "name": "Ashburn, USA (elfhosted.tbc)",
            "server" :"//speedtest-ashburn.elfhosted.com/",
            "dlURL" :"garbage.php",
            "ulURL" :"empty.php",
            "pingURL" :"empty.php",
            "getIpURL" :"getIP.php"
        },
        {
            "name": "Kansas, USA (elfhosted.tbc)",
            "server" :"//speedtest-kansascity.elfhosted.com/",
            "dlURL" :"garbage.php",
            "ulURL" :"empty.php",
            "pingURL" :"empty.php",
            "getIpURL" :"getIP.php"
        },
        {
            "name": "California, USA (elfhosted.tbc)",
            "server" :"//speedtest-freemont.elfhosted.com/",
            "dlURL" :"garbage.php",
            "ulURL" :"empty.php",
            "pingURL" :"empty.php",
            "getIpURL" :"getIP.php"
        }                         
        //...more servers...
    ]


    
    